export default {
  autocomplete:  (mode) => () => import(`./basic/autocomplete${mode}`),
  cascader: (mode) => () => import(`./basic/cascader${mode}`),
  checkbox: (mode) => () => import(`./basic/checkbox${mode}`),
  date: (mode) => () => import(`./basic/date-picker${mode}`),
  divider: (mode) => () => import(`./basic/divider${mode}`),
  editor: (mode) => () => import(`./basic/editor${mode}`),
  file: (mode) => () => import(`./basic/file${mode}`),
  image: (mode) => () => import(`./basic/image${mode}`),
  input: (mode) => () => import(`./basic/input${mode}`),
  link: (mode) => () => import(`./basic/link${mode}`),
  number: (mode) => () => import(`./basic/number${mode}`),
  password: (mode) => () => import(`./basic/password${mode}`),
  radio: (mode) => () => import(`./basic/radio${mode}`),
  rate: (mode) => () => import(`./basic/rate${mode}`),
  selectImage: (mode) => () => import(`./basic/select-image${mode}`),
  selectObject: (mode) => () => import(`./basic/select-object${mode}`),
  selectInputTable: (mode) => () => import(`./basic/select-input-table${mode}`),
  selectTable: (mode) => () => import(`./basic/select-table${mode}`),
  selectTree: (mode) => () => import(`./basic/select-tree${mode}`),
  selectTreeV2: (mode) => () => import(`./basic/select-tree-v2${mode}`),
  select: (mode) => () => import(`./basic/select${mode}`),
  singleCheckbox: (mode) => () => import(`./basic/single-checkbox${mode}`),
  slider: (mode) => () => import(`./basic/slider${mode}`),
  staticInfo: (mode) => () => import(`./basic/static-info${mode}`),
  staticOptionsConfig: (mode) => () => import(`./basic/static-options-config${mode}`),
  switch: (mode) => () => import(`./basic/switch${mode}`),
  table: (mode) => () => import(`./basic/table${mode}`),
  tableRadio: (mode) => () => import(`./basic/table-radio${mode}`),
  text: (mode) => () => import(`./basic/text${mode}`),
  textarea: (mode) => () => import(`./basic/textarea${mode}`),
  time: (mode) => () => import(`./basic/time-select${mode}`),
  tree: (mode) => () => import(`./basic/tree${mode}`),
  dateRange: (mode) => () => import(`./extension/date-range${mode}`),
  numberRange: (mode) => () => import(`./extension/number-range${mode}`),
  timeRange: (mode) => () => import(`./extension/time-range${mode}`),
  urlEditor: (mode) => () => import(`./basic/url-editor${mode}`),
  // BROKEN: 此项迁移至 @xigefish/plugins/form/form-input/request/data-dictionary
  // MIGRATION: 迁移说明 migration/v3.x.md
  // dataDictionary: {
  //   component: (mode) => () => import(`./request/data-dictionary${mode}`)
  // },
  toleranceNumber: (mode) => () => import(`./extension/tolerance-number${mode}`),
  inputTag: () => () => import('./special-view/input-tag/view'),
  multiInfoStatus: () => () => import('./special-view/multi-info-status/view'),
  versionTag: () => () => import('./special-view/version-tag/view'),
  arrayObject: () => () => import('./special-view/array-object/view'),
  auditStatus: () => () => import('./special-view/audit-status/view'),
  colorStatus: () => () => import('./special-view/color-status/view'),
  default: (mode) => () => import(`./basic/input${mode}`)
}
